server:
  port: 8003 #服务端口


spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB
  application:
    name: cloud-tweet-service #服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动包
    url: jdbc:mysql://175.24.202.178:3306/syl?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: Jwl12345
  mail:
    # 163
    host: smtp.163.com
    port:
    username: tongjsoftware@163.com
    password: AQMSTKQQHTZSYRZY
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false

devtools:
  restart:
    enabled: true #是否支持热部署

file:
  localPath: "C:\\upload"
  webPath: "http://175.24.202.178:777"